### ISSUE TITLE
[Read ME Request]: Can you please consider adding necessary packages to install?

### ISSUE THREAD

**Issue by prameshbajra** [aws-samples/amazon-textract-code-samples#10]
The repo seems great. No doubt on that.

What would make this greater is the list of libraries/modules that needs to be installed for the files to run smoothly.

Something like a `requirements.txt` would help.

**Comment by schadem** [comment]
Agree that having a requirements file would help, but also not all examples require all dependencies. 
We are moving towards a more packaging oriented example solution, check out: https://github.com/aws-samples/amazon-textract-textractor/tree/master/caller or https://github.com/aws-samples/amazon-textract-textractor/tree/master/helper for examples.
