### ISSUE TITLE
Is it possible to make async calls without uploading the document to S3 bucket? 

### ISSUE THREAD

**Issue by ayushidalmia** [aws-samples/amazon-textract-code-samples#13]
I am reading the pdf as a bytearray and pass it to my analyser as follows:

` response = self.textract.start_document_analysis(DocumentLocation={'Bytes': {docBytes}}, FeatureTypes=["TABLES", "FORMS"], NotificationChannel={'RoleArn': self.roleArn, 'SNSTopicArn': self.snsTopicArn})
`
But this gives the following error: 
`TypeError: unhashable type: 'bytearray'
`

**Comment by Eitol** [comment]
no, not currently possible
