### ISSUE TITLE
Broken blocks relations

### ISSUE THREAD

**Issue by Eitol** [aws-samples/amazon-textract-code-samples#16]
When getting more blocks than the "MaxResults" parameter, the parsing of the document fails.

![image](https://user-images.githubusercontent.com/1043061/128121128-b19e0eb3-4a53-4f70-b283-90f77ae8df47.png)

![image](https://user-images.githubusercontent.com/1043061/128121183-ddaa85f4-7c28-410d-8af8-3330cf768ad9.png)

Therefore the parse must be able to support broken references.

The failure is reproduced in the following repository:

https://github.com/Eitol/test_problematic_file

**Comment by schadem** [comment]
The Textract JSON response will not include broken references, it is consistent. I have seen this when for an asynchronous call not all the parts of the paginated response are pulled and combined. Take a look at https://github.com/aws-samples/amazon-textract-textractor/tree/master/caller for a higher level call that does that or the sample functions that get the pagininated results.
