### ISSUE TITLE
Chain of Errors

### ISSUE THREAD

**Issue by mettlus** [aws-samples/amazon-textract-code-samples#4]
py version 3 and up dont support print " "
after fixing that it threw scraper error, installed scraper still error

**Comment by darwaishx** [comment]
Which example is giving that error?

**Comment by aswinkumar2019** [comment]
Hello darwaishx,
I also get the same error while using the trp package,
I think it is outdated,i have raised the issue in https://forums.aws.amazon.com/thread.jspa?messageID=942710&#942710

Please give solution for this
Regards,
Aswin Kumar

**Comment by aswinkumar2019** [comment]
Hello guys,
I think aws documentation must be more clear. 
The trp package referred must be installed using pip3 install textract-trp and not,
pip3 install trp. 
Textract-trp is the official amazon package.
I think amazon needs to explain this in the documentation. 
Regards, 
Aswin Kumar
