### ISSUE TITLE
InvalidParameterException when starting a Textract job using SNS Notification channel.

### ISSUE THREAD

**Issue by prashanthayyavu** [aws-samples/amazon-textract-code-samples#6]
When I start a textract StartDocumentTextDetection and try to set the NotificationChannel as follows
 
```python
 response = client.start_document_text_detection(
        DocumentLocation={
            'S3Object': {
                'Bucket': s3BucketName,
                'Name': objectName
            },
        },
        ClientRequestToken='string',
        JobTag='string',
        NotificationChannel={
            'RoleArn': snsRoleArn,
            'SNSTopicArn': snsTopicArn
        }
    )
```

I am getting an InvalidParameterException

An error occurred (InvalidParameterException) when calling the StartDocumentTextDetection operation: Request has invalid parameters

python 3.7
boto3  1.12.35

**Comment by darwaishx** [comment]
https://github.com/aws-samples/amazon-textract-serverless-large-scale-document-processing
Sample implementation above has example of passing SNS info to start call.
