### ISSUE TITLE
Bug in parsing for Document

### ISSUE THREAD

**Issue by tshrjn** [aws-samples/amazon-textract-code-samples#9]
When parsing some multi-page outputs, there's a bug in the `trp.py` file.
Due to which the keys in the ` blockmap` at line [119](https://github.com/aws-samples/amazon-textract-code-samples/blob/master/python/trp.py#L119) is not found & `KeyError Exception`  is thrown.

**Comment by stephenh20** [comment]
Had same problem, even though the code loops over pages first it seems that it cannot find things that are on subsequent pages. I placed if cid in blockMap: around line 119 which resulted in getting the keys found for page1 only in a three page pdf.
If I split the pdf into 3 separate pages I get the expected results for each page.
The code has a loop around the pages but it cant seem to find anything past page 1 in trp.Document(response)

**Comment by tshrjn** [comment]
@stephenh20 Did you find a workaround or did you have some script which breaks into separate pages uses the parser on each separately & stitches them later on?

**Comment by stephenh20** [comment]
I split the pdf into pages then work on the pages separately.
I then search through each page to see if the info I nee is there.

**Comment by mcaires2** [comment]
Hey Guys, 
I am  from Brazil. I am not a expert on coding (only do it for my personal projects)..
Look at my github at: 

https://github.com/mcaires2/textratc_with_aws_pdf_multiple_pages_tables_text/blob/master/textract_tables_pdf_multiple_pages_to_excel.py

From the readmeEnglish look to this part:

"Extracting **text** from a PDF went smoothly when the file has many pages.
The same cannot be said when we went to extract **tables**. In this case, when the return file has more than one batch ('token'), an error occurred to find a key when building the tables whose information was in the first and second batch.
We get around this using a simple technique of looping forwards in the 'pages' list and adding (+)(not append) all the blocks ['Blocks'] before building the tables."

contador=0                                                          # ( translating to English 'contador" means  counter)  it is just a integer variable
    csv = ''
    blocks=[]
    for item in pages:
      blocks= blocks + pages[contador]['Blocks']                                                #  when you have tables on more than one Token 
      contador= contador+1
    print(contador)

**Comment by tshrjn** [comment]
Actually, the issue I was facing was a bit different, when I tried to search for the missing blockid, the textract response didn't actually have that block but it did have in CHILD relationships.

There were many "LINE" blocks (~9% from 200 docs) that had CHILD relationships with **all** `child blockID` for the words in the sentence that were missing from the api's response.

So, the issue in my case was from textract's response.

**Comment by schadem** [comment]
I added a package and method to call Textract which also works for paginated output. https://github.com/aws-samples/amazon-textract-textractor/tree/master/caller
Just use call_textract from that and you'll be good.
Closing this for now
